ERROR:root:No token file found. Also make sure that a [prod] section with a 'token = value' assignment exists.
usage: main_80_20.py [-h] [--cfg_file CFG_FILE] [--model_name MODEL_NAME]
                     [--use_sop USE_SOP] [--batch_size BATCH_SIZE]
                     [--eval_steps EVAL_STEPS]
                     [--evaluation_strategy EVALUATION_STRATEGY]
                     [--gradient_accumulation_steps GRADIENT_ACCUMULATION_STEPS]
                     [--warmup_steps WARMUP_STEPS] [--save_steps SAVE_STEPS]
                     [--logging_steps LOGGING_STEPS]
                     [--train_batch_size TRAIN_BATCH_SIZE]
                     [--git_checkpoint GIT_CHECKPOINT]
                     [--eval_checkpoint EVAL_CHECKPOINT]
                     [--resume_from_checkpoint RESUME_FROM_CHECKPOINT]
                     [--per_device_train_batch_size PER_DEVICE_TRAIN_BATCH_SIZE]
                     [--per_device_eval_batch_size PER_DEVICE_EVAL_BATCH_SIZE]
                     [--do_train DO_TRAIN] [--do_eval DO_EVAL]
                     [--do_eval_partial DO_EVAL_PARTIAL]
                     [--do_preprocess DO_PREPROCESS]
                     [--do_dump_dict_gt DO_DUMP_DICT_GT]
                     [--adam_epsilon ADAM_EPSILON]
                     [--dataset_train_len DATASET_TRAIN_LEN]
                     [--dataset_eval_len DATASET_EVAL_LEN]
                     [--learning_rate LEARNING_RATE] [--local-rank LOCAL_RANK]
                     [--dispatch_batches DISPATCH_BATCHES]
                     [--reset_model RESET_MODEL]
                     [--weighted_crossentropy WEIGHTED_CROSSENTROPY]
                     [--adam_beta1 ADAM_BETA1] [--adam_beta2 ADAM_BETA2]
                     [--num_train_epochs NUM_TRAIN_EPOCHS] [--epochs EPOCHS]
                     [--workers WORKERS] [--extra_tag EXTRA_TAG] [--ckpt CKPT]
                     [--pretrained_model PRETRAINED_MODEL]
                     [--launcher {none,pytorch,slurm}] [--tcp_port TCP_PORT]
                     [--sync_bn] [--fix_random_seed FIX_RANDOM_SEED]
                     [--ckpt_save_interval CKPT_SAVE_INTERVAL]
                     [--max_ckpt_save_num MAX_CKPT_SAVE_NUM]
                     [--merge_all_iters_to_one_epoch] [--set ...]
                     [--max_waiting_mins MAX_WAITING_MINS]
                     [--start_epoch START_EPOCH]
                     [--num_epochs_to_eval NUM_EPOCHS_TO_EVAL]
                     [--save_to_file]
                     [--remove_unused_columns REMOVE_UNUSED_COLUMNS]
                     [--dataloader_pin_memory DATALOADER_PIN_MEMORY]
                     [--fuse_conv_bn] [--output_dir OUTPUT_DIR]
                     [--log3dnet_dir LOG3DNET_DIR]
                     [--save_hit_file SAVE_HIT_FILE]
                     [--id_max_length ID_MAX_LENGTH] [--eval_chkt EVAL_CHKT]
main_80_20.py: error: unrecognized arguments: / /
